name: Deployment

on:
  push:
    branches:
      - main

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    environment:
      name: Development

  prod-deploy:
    runs-on: ubuntu-latest
    needs: dev-deploy
    environment:
      name: Production
