name: Deployment

on:
  push:
    branches:
      - main

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    environment:
      name: Development
    steps:
      - run: echo "Deploying to Development Environment"

  staging-deploy:
    runs-on: ubuntu-latest
    needs: dev-deploy
    environment:
      name: Staging
    steps:
      - run: echo "Deploying to Staging Environment"

  prod-deploy:
    runs-on: ubuntu-latest
    needs: staging-deploy
    environment:
      name: Production
    steps:
      - run: echo "Deploying to Production Environment"
