name: release-automation

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-automation:
    runs-on: ubuntu-latest
    steps:
      - name: release-please-action
        uses: google-github-actions/release-please-action@v3.1.2
        with:
          release-type: node
          package-name: package.json
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
